### ISSUE TITLE
Patch for /trunk/EDB.cpp

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jwhiddon/arduino-edb#4]
```
make it work in arduino 1.+
keeping compatibility with earlier versions
```

Original issue reported on code.google.com by `yai...@gmail.com` on 1 Nov 2012 at 9:44

Attachments:
* [EDB.cpp.patch](https://storage.googleapis.com/google-code-attachments/arduino-edb/issue-4/comment-0/EDB.cpp.patch)

**Comment by jwhiddon** [comment]
Fixed
